# gitops filder

# create placement objects if not created
oc create -f gitops/placements/apps-placement.yaml
oc create -f gitops/placements/location-placement.yaml


# create hub-apis sa and generate token with cluster-admin role
oc create sa hub-apis
# create token valid for 10days
oc create token hub-apis --duration 14400m
# a secret will be created with the token that can be used fot he API calls (hub-apis-token-XXXXX)
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:hub-ns:hub-apis
# curl -k -H "Authorization: Bearer TOKEN" "https://api.cluster-sql9s.sql9s.[Base DNS Domain]:6443/apis/policy.open-cluster-management.io/v1/namespaces/openshift-gitops/policies/hub-ns"


# create hub-apis-token secret
cat <<EOF | oc apply -f -
kind: Secret
apiVersion: v1
metadata:
  name: hub-apis-token
  namespace: hub-ns
data:
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltOTZlamhvZG1WTlZVTnBPSEJxVG14aE5EbEVURXhzT1U4M1RHRnpUV05HYjNGTk1rSk1URzV3WW1NaWZRLmV5SmhkV1FpT2xzaWFIUjBjSE02THk5cmRXSmxjbTVsZEdWekxtUmxabUYxYkhRdWMzWmpJbDBzSW1WNGNDSTZNVGN6T1RjeE56Y3pOeXdpYVdGMElqb3hOek00T0RVek56TTNMQ0pwYzNNaU9pSm9kSFJ3Y3pvdkwydDFZbVZ5Ym1WMFpYTXVaR1ZtWVhWc2RDNXpkbU1pTENKcWRHa2lPaUpsTWpVNE1tRm1OaTB3TVdNMUxUUmpNVE10WVRnM01DMDRaR1V5TURka01EQmxOV1lpTENKcmRXSmxjbTVsZEdWekxtbHZJanA3SW01aGJXVnpjR0ZqWlNJNkltaDFZaTF1Y3lJc0luTmxjblpwWTJWaFkyTnZkVzUwSWpwN0ltNWhiV1VpT2lKb2RXSXRZWEJwY3lJc0luVnBaQ0k2SWpObVptUmpaR0prTFRVd1pHVXROR05pWWkxaFlXVTRMVFZqTXpjeU4ySTFZVGs0TVNKOWZTd2libUptSWpveE56TTRPRFV6TnpNM0xDSnpkV0lpT2lKemVYTjBaVzA2YzJWeWRtbGpaV0ZqWTI5MWJuUTZhSFZpTFc1ek9taDFZaTFoY0dsekluMC5YLWFjcmJTMTEwTVZYb3pGRE14X0Q2SFJ6c1VJNEVuRzZvMk1BMUdjdC0xeWtRM0lMWTBkRDBLUE11ZTJRdlZyUXZYVjdCLWpZWEF2Vm9tMjNLUnRCNkZTeXAtblpXajl4cWZaUEpHYnFYMEZTVzd3UnhxcHpJMmtOdkRQRzR1UmlHQnRzUGFYUExwUnhmbmhDMW9OM3VRdlNCaUNFejByeEFGNjFIN0xTcEdTUlZqUExrVUotMHdlcTNrbVRkQ25VWnIyUnFranN2aDFZNlpGaHg5SkdpSm5lQmgyWkNyZnBQNkhkQ3RMRTlGQ25jTEVRWHN1MS1qMVgyMXdUSlF5YUdpMW54eXNVOGt1d281dWFGUng2TC1NeGx2WkVNYkY4VnhlRGNyeGNUMUR4cmxwYURjSUZEaEtpUDJpNk5sZXR1cTJldnNDaHlnbVhxaHRocTVGeHhLVlRoTW5STlE1NnEySHNuTDFmaGI5SFNhRXhlQUVISEp5Z1ZMOGN3bEZpeWZWNjhZSmYxci1xeGFFZm1WajdWdFNmLTVoXzM0anpZN2xKTXVIc2pfY3NWeHI2QWxlczEweEdsZV92RGFfdG03eWVzVkJ1VnphYS1PYzY4b01fUTdoRE5sOUpvVDZUWW9uZXU1MFBDZ3FyUHRXMFJfYnpZd2FzakZ1TGt2d1ctdkQ2T3RIUmxhdW9qLWt5UEI4SlQ0RmlXd1MtbF9iU1plZTZHVTROVDlpZWhaSlo1eUVnTWRhbHRZcWV0c0JyY2U5ZHk5Uy10a0RjclZPekVyV2FJRnk2VEFISTdDV1ZnS0lzaVFzd2pyQTlPODJ4TGVlclBZMFo2RXVQblVNMFczTGNxYkcteHg5alFPTWlYZy1FMGFCblEydnJpYzd3Y05iRjJNanU1aw==
type: Opaque
EOF

oc create -f gitops/placements/argocd-placement.yaml


# once secret is created, then deploy the dashboard app
# deploy dashboard app
oc create -f gitops/dashboard-applicationset.yaml -n openshift-gitops



# delete 
#oc delete  -f gitops/dashboard-applicationset.yaml -n openshift-gitops

