kind: Secret
apiVersion: v1
metadata:
  name: cluster-secrets
data:
  cluster: # content of cluster.yaml
  cluster-set: # content of cluster-set.yaml
  secrets: # content of cluster-secrets-list.yaml
type: Opaque
