apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: provisioning-callback
spec:
  description: Send Provisioning callback
  params:
    - default: 'pss'
      description: department
      name: department
      type: string
    - name: callback_url
      type: string
      default: "http://dashboard-hub-ns.apps.cluster-t6rzf.t6rzf.sandbox312.opentlc.com/provision/commit"
  workspaces:
    - name: workspace
  steps:
    - name: configure
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |
        #!/usr/bin/env bash

        curl -XPOST -d '{"name": "$(params.department)"}' $(params.callback_url) -H 'Content-Type: application/json'