apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: SYSTEM
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: DEPARTMENT-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: SYSTEM-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      sources:
        - repositoryType: git
          #repoURL: https://github.com/levenhagen/rocketchat-acm.git
          repoURL: https://github.com/wael2000/dora.git
          targetRevision: main
          path: gitops/apps/LOCATION/DEPARTMENT/SYSTEM
          #path: rocketchat
      destination:
        namespace: DEPARTMENT
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true