kind: Secret
apiVersion: v1
metadata:
  name: postgresql
data:
  database-name: ZnNp #fsi
  database-password: QzBtcGxleFBAc3N3MHJk #C0mplexP@ssw0rd
  database-user: cG9zdGdyZXNAcG9zdGdyZXNxbHNlcnZlci1mc2k= #postgres@postgresqlserver-fsi
type: Opaque